name: Renovate

on:
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch: {}
  push:
    branches: [main]
    paths:
      - "renovate.json"
      - ".github/workflows/renovate.yml"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v46.2.5
        with:
          configurationFile: renovate.json
          token: "${{ secrets.RENOVATE_TOKEN }}"
        env:
          RENOVATE_REPOSITORIES: "${{ github.repository }}"
